/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glywk_jnisrv_OperationFacade */

#ifndef _Included_com_glywk_jnisrv_OperationFacade
#define _Included_com_glywk_jnisrv_OperationFacade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glywk_jnisrv_OperationFacade
 * Method:    getBasicAction
 * Signature: ()Lcom/glywk/jnisrv/MessageResultWrapper;
 */
JNIEXPORT jobject JNICALL Java_com_glywk_jnisrv_OperationFacade_getBasicAction
  (JNIEnv *, jclass);

/*
 * Class:     com_glywk_jnisrv_OperationFacade
 * Method:    postStringAction
 * Signature: (Ljava/lang/String;)Lcom/glywk/jnisrv/MessageResultWrapper;
 */
JNIEXPORT jobject JNICALL Java_com_glywk_jnisrv_OperationFacade_postStringAction
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
